"""
SQLite Database Creation Script for SMB Business Application
Creates database schema WITHOUT dummy data - ready for users to add their own data
"""
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

def create_database():
    """Create empty Postgres database with complete schema"""
    
    # Database connection parameters
    params = {
        "host": "localhost",
        "database": "smb_one_db",
        "user": "postgres",
        "password": "Rajnikant@1",
        "port": 5432 # Default port is 5432
    }
        
    print('Connecting to the PostgreSQL database...')
    conn = psycopg2.connect(**params)
    conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    cursor = conn.cursor()
    
    print("🗄️  Creating database schema...")
    
    # =====================================================================
    # TABLE SCHEMAS
    # =====================================================================
    
    # Users table for authentication
    cursor.execute('''
    CREATE TABLE users (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL,
        security_question TEXT NOT NULL,
        security_answer TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    ''')
    
    # Categories
    cursor.execute('''
    CREATE TABLE categories (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT UNIQUE NOT NULL,
        description TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id INTEGER NOT NULL REFERENCES users(id)
    )
    ''')
    
    # Suppliers
    cursor.execute('''
    CREATE TABLE suppliers (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        contact_person TEXT,
        email TEXT,
        phone TEXT,
        address TEXT,
        rating REAL DEFAULT 0.0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id INTEGER NOT NULL REFERENCES users(id)
    )
    ''')
    
    # Products
    cursor.execute('''
    CREATE TABLE products (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        sku TEXT UNIQUE NOT NULL,
        price REAL NOT NULL,
        cost REAL NOT NULL,
        stock INTEGER DEFAULT 0,
        reorder_level INTEGER DEFAULT 10,
        supplier_id INTEGER REFERENCES suppliers(id),
        last_restock_date DATE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id INTEGER NOT NULL REFERENCES users(id)
    )
    ''')
    
    # Customers
    cursor.execute('''
    CREATE TABLE customers (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        email TEXT,
        phone TEXT,
        company TEXT,
        address TEXT,
        city TEXT,
        state TEXT,
        segment TEXT DEFAULT 'Individual',
        total_purchases REAL DEFAULT 0.0,
        last_purchase_date DATE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id INTEGER NOT NULL REFERENCES users(id)
    )
    ''')
    
    # Sales
    cursor.execute('''
    CREATE TABLE sales (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        date DATE NOT NULL,
        product_id INTEGER REFERENCES products(id),
        product_name TEXT NOT NULL,
        category TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        unit_price REAL NOT NULL,
        revenue REAL NOT NULL,
        cost REAL NOT NULL,
        profit REAL NOT NULL,
        customer_id INTEGER REFERENCES customers(id),
        region TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id INTEGER NOT NULL REFERENCES users(id)
    )
    ''')
    
    # Contracts
    cursor.execute('''
    CREATE TABLE contracts (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        contract_id TEXT UNIQUE NOT NULL,
        client_name TEXT NOT NULL,
        value REAL NOT NULL,
        start_date DATE NOT NULL,
        end_date DATE NOT NULL,
        status TEXT DEFAULT 'Pending',
        description TEXT,
        signed_date DATE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id INTEGER NOT NULL REFERENCES users(id)
    )
    ''')
    
    # Financial Transactions
    cursor.execute('''
    CREATE TABLE transactions (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        date DATE NOT NULL,
        description TEXT NOT NULL,
        amount REAL NOT NULL,
        type TEXT NOT NULL, -- 'Income' or 'Expense'
        category TEXT,
        status TEXT DEFAULT 'Completed',
        reference_number TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id INTEGER NOT NULL REFERENCES users(id)
    )
    ''')
    
    # Shipments
    cursor.execute('''
    CREATE TABLE shipments (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        tracking_number TEXT UNIQUE NOT NULL,
        order_id TEXT NOT NULL,
        customer_id INTEGER REFERENCES customers(id),
        status TEXT DEFAULT 'Processing',
        origin TEXT,
        destination TEXT,
        ship_date DATE,
        delivery_date DATE,
        weight REAL,
        shipping_cost REAL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id INTEGER NOT NULL REFERENCES users(id)
    )
    ''')
    
    # Milestones (for user-defined milestones)
    cursor.execute('''
    CREATE TABLE milestones (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        title TEXT NOT NULL,
        description TEXT,
        target_value REAL NOT NULL,
        current_progress REAL DEFAULT 0.0,
        unit TEXT NOT NULL, -- 'revenue', 'sales', 'customers', etc.
        target_date DATE NOT NULL,
        status TEXT DEFAULT 'active', -- 'active', 'completed', 'paused'
        created_date DATE DEFAULT CURRENT_DATE,
        completed_date DATE,
        user_id INTEGER NOT NULL REFERENCES users(id)
    )
    ''')
    
    conn.commit()
    print("✅ Database schema created")

    # =====================================================================
    # SUMMARY
    # =====================================================================
    
    print("\n" + "="*70)
    print("🗄️  DATABASE CREATED SUCCESSFULLY")
    print("="*70)
    print("📋 TABLES CREATED:")
    
    tables = [
        ('users', 'Users'),
        ('categories', 'Categories'), 
        ('suppliers', 'Suppliers'),
        ('products', 'Products'),
        ('customers', 'Customers'),
        ('sales', 'Sales'),
        ('contracts', 'Contracts'),
        ('transactions', 'Financial Transactions'),
        ('shipments', 'Shipments'),
        ('milestones', 'Milestones')
    ]
    
    for table_name, display_name in tables:
        cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
        count = cursor.fetchone()[0]
        print(f"{display_name:.<35} {count:>10,} records")
    
    print("="*70)
    print(f"✅ Empty database created successfully: {params['database']}")
    print("📝 Ready for users to add their own data!")
    print("="*70)
    
    conn.close()

if __name__ == "__main__":
    create_database()